---
collections:
  # Default collections
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.windows
  - name: awx.awx
  - name: azure.azcollection
  - name: community.vmware
  - name: google.cloud
  - name: kubernetes.core
  - name: openstack.cloud
  - name: ovirt.ovirt
  - name: redhatinsights.insights
  - name: theforeman.foreman
  # Additional custom collections
  - name: fortinet.fortios
  - name: community.aws
  - name: community.crypto
  - name: community.general
  - name: community.hashi_vault
  - name: community.windows
  - name: community.docker
  - name: community.postgresql
  - name: community.mysql
  - name: community.rabbitmq
  - name: community.grafana
