name: auto-release

on:
  push:
    branches:
      - main
      - master
      - production
  # pull_request:
  #   types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_INSTALLATION_ID }}

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ github.event_name != 'pull_request' }}
          prerelease: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
