name: auto-release

on:
  push:
    branches:
      - main
      - master
      - production
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_INSTALLATION_ID }}

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ github.event_name != 'pull_request' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
